charts/images.yaml
*Release Notes*:
``` improvement operator github.com/gardener/cert-management #18 @MartinWeindel
If a DNS nameserver for prechecking DNS propagation are not reachable by UDP, the DNS query request is retried with TCP.
```
``` improvement operator github.com/gardener/cert-management #18 @MartinWeindel
The DNS nameservers for prechecking can be specified by command line option --precheck-nameservers
```
``` improvement operator github.com/gardener/cert-management #18 @MartinWeindel
Added command line option --precheck-additional-wait to wait for last mile record propagation to the DNS server used by the ACME server
```
``` improvement operator github.com/gardener/cert-management #17 @Diaphteiros
Add missing translation from helm values file to controller arguments for 'dns-class' and …
```
=> [ci:component:github.com/gardener/cert-management:v0.2.13->v0.2.14]

charts/internal/shoot-cert-management-shoot/templates/crds.yaml
fix for certificate crd validation. The field `lastPendingTimestamp` in the status is not required. This prevents creating new certificates.
Fixes #
```improvement user
validation: remove lastPendingTimestamp as required field in status
```
=> remove lastPendingTimestamp as required field in status

charts/internal/shoot-cert-management-shoot/templates/crds.yaml
/area robustness
/kind bug
/priority normal
This PR removes the `status.lastPendingTimestamp` from the certificate CR to workaround this status update issue: https://github.com/gardener/cert-management/issues/31.
```improvement user
An issue has been fixed which caused certificates to not get ready if the TLS certificate was successfully issued before.
```
=> Remove lastPendingTimestamp from CRD

charts/images.yaml, charts/internal/shoot-cert-management-shoot/templates/crds.yaml
cert-management:v0.2.15->v0.2.16
Fixes #
``` improvement operator github.com/gardener/cert-management #30 @MartinWeindel
allow to specify a quota for certificate requests per day
```
``` improvement operator github.com/gardener/cert-management #30 @MartinWeindel
lease mechanism is activated for all controllers to allow running multiple instances
```
``` improvement user github.com/gardener/cert-management #30 @MartinWeindel
allow to set certificate secret reference without setting 'secretName' field
```
``` improvement user github.com/gardener/cert-management #30 @MartinWeindel
validate for duplicate domain names in certificate
```
``` improvement operator …
```
=> updated to cert-management v0.2.16

charts/internal/shoot-cert-management-seed/templates/deployment.yaml
This PR adds the appropriate Gardener netpol label to let the Cert-Management controller talk to public networks.
```improvement operator
Required network policies for Cert-Management have been aligned with the latest changes from Gardener (https://github.com/gardener/gardener/pull/2339).
```
=> Fix netpol label for cert-management

pkg/controller/actuator.go
Currently the shoot-cert-service panics when the Extension `spec.providerConfig=nil`:
```
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1835ec0, 0x2a0ff70)
/go/src/github.com/gardener/gardener-extension-shoot-cert-service/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/src/github.com/gardener/gardener-extension-shoot-cert-service/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1835ec0, 0x2a0ff70)
/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/gardener/gardener-extension-shoot-cert-service/pkg/controller.(*actuator).updateStatus(0xc0004b70e0, 0x1caff00, 0xc000c98d40, 0xc0007e49c0, 0x0, 0xc000c52240, 0x18) …
```
=> Fix nil pointer when spec.providerConfig=nil

charts/internal/shoot-cert-management-seed/templates/deployment.yaml, charts/internal/shoot-cert-management-shoot/templates/cert-management-role.yaml, charts/internal/shoot-cert-management-shoot/templates/cert-management-rolebinding.yaml, pkg/controller/actuator.go
Currently cert-controller-manager fails to acquire leadership because of missing RBAC:
```
E0709 14:52:43.176146       1 leaderelection.go:330] error retrieving resource lock shoot--foo--bar/cert-controller-manager: configmaps "cert-controller-manager" is forbidden: User "gardener.cloud:system:cert-management" cannot get resource "configmaps" in API group "" in the namespace "shoot--foo--bar"
E0709 14:52:45.445372       1 leaderelection.go:330] error retrieving resource lock shoot--foo--bar/cert-controller-manager: configmaps "cert-controller-manager" is forbidden: User "gardener.cloud:system:cert-management" cannot get resource "configmaps" in API group "" in the namespace "shoot--foo--bar"
```
This PR adds the missing RBAC.
**Which issue(s) this …
=> Fix cert-controller-manager leader election

docs/installation/setup.md, docs/usage/request_cert.md
/priority normal
/area documentation 
There's a relative link to dns names guide a the top of the document, which I converted to absolute and pointing to the dns_names.md guide that will be merged with gardener/gardener-extension-shoot-dns-service#30
=> Moving cert management docs from /documentation

charts/internal/shoot-cert-management-seed/templates/vpa.yaml
/area scalability
/priority normal
Add minAllowed resources for the cert-controller VPA
/cc @BeckerMax 
```improvement operator
The VPA configuration for the `cert-controller-manager` deployment in the shoot namespaces in the seed is now enforcing at least `10m` CPU and `20Mi` memory requests.
```
=> Add minAllowed resources for the cert-controller VPA

charts/internal/shoot-cert-management-seed/templates/deployment.yaml
/area control-plane robustness high-availability
/kind bug
/priority normal
Cert-controller-manager has to be labelled as controlplane to be restarted by DependencyWatchDog if kube-apiserver recovers
Fixes https://github.com/gardener/gardener-extension-shoot-cert-service/issues/64
```other operator
add controlplane role for cert-manager-controller
```
=> add controlplane role for cert-manager-controller

.ci/component_descriptor
fix component descriptor script for release
same as https://github.com/gardener/gardener-extension-shoot-dns-service/pull/62
```other operator
```
=> fix component descriptor script

charts/internal/shoot-cert-management-seed/templates/deployment.yaml, charts/internal/shoot-cert-management-shoot/templates/cert-management-role.yaml
/kind technical-debt
Add permissions for using leases in the `cert-controller-manager` running the control plane.
With PR https://github.com/gardener/cert-management/pull/79, the next version v0.7.1 will use both configmaps and leases.
Fixes #
```other operator
Add permissions for leader election lease of cert-controller-manager in control plane
```
=> Add permissions for leader election lease of cert-controller-manager in control plane

charts/internal/shoot-cert-management-seed/templates/deployment.yaml
/kind cleanup
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/422
Ref gardener/gardener#1649
```other operator
NONE
```
=> Remove the "garden.sapcloud.io/role" label from control plane components

Dockerfile, charts/internal/shoot-cert-management-seed/templates/deployment.yaml, docs/usage/request_cert.md, example/30-extension.yaml, hack/api-reference/service.md, pkg/apis/config/validation/validation.go, pkg/apis/service/types.go, pkg/apis/service/v1alpha1/types.go, pkg/apis/service/v1alpha1/zz_generated.conversion.go, pkg/apis/service/v1alpha1/zz_generated.deepcopy.go, pkg/apis/service/validation/validation.go, pkg/apis/service/validation/validation_test.go, pkg/apis/service/zz_generated.deepcopy.go, pkg/controller/actuator.go
Support ACME providers on private network and allow to specify `precheckNameservers` in the `providerConfig` of the extension.
Fixes #107
```other user
Allow access to ACME CA on private network.
```
=> ACME providers on private network

charts/internal/shoot-cert-management-seed/templates/rbac.yaml
/kind bug
Permissions have been missing to create events if issuer creation fails.
Fixes #
```bugfix operator
Add permissions to create events in control plane if issuer creation fails.
```
=> Add permissions to create events in control plane

charts/internal/shoot-cert-management-seed/templates/vpa.yaml, charts/internal/shoot-cert-management-seed/values.yaml
/area auto-scaling
/area robustness
Sets absolute memory limit for the shoot-cert-management-seed container per measured actual usage. Removes CPU limit of same container. Disables limit autoscaling.
Fixes #
```other operator
A fixed memory limit was set for the shoot-cert-management-seed container, in accordance with measurements of actual field usage. CPU limit of same container was removed.
```
=> Update limits limit. Disable limit autoscaling.

charts/internal/shoot-cert-management-seed/cert-dashboard.json
/area monitoring
Adjust metric name due to upgrading the kube-state-metrics component
See https://github.com/gardener/gardener/pull/6224
Fixes #
/cc @wyb1 @ialidzhikov
```other operator
Adjust metric name due to upgrading the kube-state-metrics component
```
=> Adjust metric name due to upgrading the kube-state-metrics component

.ci/pipeline_definitions, Dockerfile
Update builder image to golang:1.19.5
Enable clean-snapshots
Fixes #
```other operator
Update builder image to golang:1.19.5
```
=> Update builder image to golang:1.19.5

go.mod, go.sum, pkg/controller/healthcheck/add.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go, vendor/modules.txt
/kind bug
Cherry-pick of #154  on release-v1.30.
Fixes #
```bugfix operator
The stale healthcheck conditions from the `shoot-cert-service` extension are now properly cleaned up.
```
```other dependency
The following dependency is updated:
- github.com/gardener/gardener: v1.65.0 -> v1.65.3
```
=> [release-v1.30] Vendor `gardener@1.65.3` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`

charts/internal/shoot-cert-management-shoot/templates/crds-v1.yaml, docs/usage/request_cert.md, docs/usage/request_default_domain_cert.md
cert-management version 0.10.3 introduced the section `secretLabels` for certificates. CRD and docu are updated accordingly.
Fixes #
```other operator
NONE
```
=> Add secretLabels section to certificates CRD

Dockerfile, charts/internal/shoot-cert-management-seed/cert-dashboard.json
Add dashboard panel for certificate object expire date.
Fixes #
```other operator
Add dashboard panel for certificate object expire date.
```
```other operator
Updated golang from version `1.20.4` to `1.20.5`.
```
=> Add dashboard panel for certificate object expire date

charts/internal/shoot-cert-management-seed/templates/configmap-observability.yaml, charts/internal/shoot-cert-management-seed/values.yaml
/area monitoring
New metrics "cert_management_cert_object_expire" added, based on the new metrics adding alert to monitor the certificate object expiration date, if less than 3 days, sending emails to operator and users. 
Fixes #
NONE
```other operator
```
=> add certificate expiration alert

charts/internal/shoot-cert-management-seed/templates/configmap-observability.yaml
/area monitoring
/kind bug
If a cluster contains misconfigured certificates, the metrics `cert_management_cert_object_expire` reports a value of 0 and the alerting is triggered as the certificate seems to have expired since about 19600 days.
To exclude such false alerts, the expression has been adapted. 
Fixes #
```bugfix operator
No alerting for certificates in error state
```
=> No alerting for certificates in error state

charts/internal/shoot-cert-management-shoot/templates/crds-v1.yaml
/area usability
/kind bug
Add `resources.gardener.cloud/skip-health-check=true` annotation to CRDs. Otherwise, `gardener-resource-manager` might recreate them too fast during shoot deletion after `gardenlet` just deleted them (and expects them to be gone). This can lead to race conditions, especially after https://github.com/gardener/gardener/issues/7473.
This is just a workaround for now and needs to be figured out properly.
/cc @ScheererJ 
```bugfix operator
The `CustomResourceDefinition`s deployed to shoot clusters are now annotated with `resources.gardener.cloud/skip-health-check=true` to prevent `gardener-resource-manager` from recreating them too fast during …
```
=> Add `resources.gardener.cloud/skip-health-check=true` annotation to CRDs

charts/internal/shoot-cert-management-shoot/templates/crds-v1.yaml
/area usability
/kind bug
Add shoot.gardener.cloud/no-cleanup=true label to CRDs to avoid Gardenlet to delete CRDs and GRM recreating them.
As certificates have no infrastructure resources , it is not mandatory to delete them (or their source objects) in the shoot cluster.
Additionally reverts https://github.com/gardener/gardener-extension-shoot-cert-service/pull/194 as not needed anymore.
Fixes #
```bugfix operator
The `CustomResourceDefinition`s deployed to shoot clusters are now labelled with `shoot.gardener.cloud/no-cleanup=true` to prevent `gardenlet` to deleting them during shoot deletion.
```
=> Add shoot.gardener.cloud/no-cleanup=true label to CRDs

charts/internal/shoot-cert-management-seed/values.yaml
/area auto-scaling
/kind bug
With https://github.com/gardener/gardener-extension-shoot-cert-service/pull/284 we make VPA to scale requests only and no longer to scale limits proportionally. However, with this the configured memory limit of 600Mi can lead to OOMKills for some Pods. 
Following https://github.com/gardener/gardener/blob/master/docs/usage/shoot_pod_autoscaling_best_practices.md, this PR removes the memory limit.
N/A
N/A
```other operator
The memory limit from the `cert-controller-manager` Deployment is now removed.
```
=> Remove memory limit from the cert-controller-manager Deployment

charts/internal/shoot-cert-management-seed/values.yaml
/kind bug
/area auto-scaling
Cherry pick of #286 on release-v1.44.
#286: Remove memory limit from the cert-controller-manager Deployment
**Release Notes:**
```other operator
The memory limit from the `cert-controller-manager` Deployment is now removed.
```
=> [release-v1.44] Automated cherry pick of #286: Remove memory limit from the cert-controller-manager Deployment

charts/internal/shoot-cert-management-seed/templates/vpa.yaml, charts/internal/shoot-cert-management-seed/values.yaml
/area auto-scaling
Reduce default values for resource utilisation of shoot-dns-service controller in the control plane.
Additionally, its VPA is made optional for consistency reasons.
Fixes #
```other operator
Reduce default values for resource utilisation of cert-management controller in the control plane.
```
=> Improve resource utilization of cert-management controller

charts/internal/shoot-cert-management-seed/templates/vpa.yaml
/kind task
Using VPA for sudden CPU spikes while the component is mostly dormant causes needless disruptions and wastes resources twofold: VPA has a minimum slice/resolution of 10m/10M, so it cannot recommend any value below 10m CPU even if this component consumes only 1m on average and 2m in the 95th percentile.
Fixes #
```other operator
Vertical scaling on CPU dropped in VPA resource
```
=> Vertical scaling on CPU dropped in VPA resource

docs/tutorials/tutorial-custom-domain-with-istio.md
/area documentation
Replaced shortcodes with improved Hugo blockquote syntax.
This way, notes will be rendered the same way in GitHub and the websites.
Fixes #
```doc developer
NONE
```
=> Replaced shortcodes

.ci/pipeline_definitions, .ci/verify
/area dev-productivity
/kind task
Drop redundant check step, as it is now executed by Prow check job `pull-extension-shoot-cert-service-unit`.
Fixes #
```other operator
NONE
```
=> Drop redundant check step

pkg/controller/extension/actuator.go, pkg/controller/extension/deployer.go, pkg/controller/extension/deployer_test.go
/kind bug
The refactoring in PR #357 introduced a regression bug. The resources from the cluster are not set for shoot deployments. 
As a consequence, if a custom issuer with a `privateKeySecretName` is defined in the shoot manifest, the referenced secret is not found anymore.
It reports an error like
```
Error reconciling Extension: failed to lookup referenced private key secret for issuer <issuer>: invalid referenced resource: <name>
```
This PR provides a fix.
Fixes #
```bugfix user
Fix lookup of referenced secret for custom issuer in shoot manifest with `privateKeySecretName` specified.
```
=> Set resources for shoot deployment

Makefile, test/integration/extension/extension_suite_test.go, test/integration/extension/reconcile_test.go
/area testing
Add integration test for extension reconciliation if shoot manifest specifies an own issuer with a `privateKeySecretName`.
Fixes #
Follow-up of #403 
```other operator
NONE
```
=> Add integration test for shoot with own issuer and private secret key

docs/operations/deployment.md
/area documentation
Update `resources` section of example operator extension to include `clusterCompatibility` and `autoEnable` to reflect last changes in Gardener.
Fixes #
Missed to update in #415 
```docu operator
Update `resources` section of example operator extension to include `clusterCompatibility` and `autoEnable`
```
=> Update `resources` section of example operator extension

pkg/controller/extension/shared/deployer_issuers.go, pkg/controller/extension/shared/deployer_test.go
With PR [cert-management#512](https://github.com/gardener/cert-management/pull/512) the `Issuer` resources must have the `cert.gardener.cloud/class` as specified in the deployment of the cert-controller-manager. Formerly it was only required for `Certificate` resources. It was introduced to avoid races if two instances of the cert-controller-manager use the same namespace for its issuer and only reconcile their own issuers.
Fixes #
Change will only be effective with the next release of the cert-management.
```other operator
Add annotation `cert.gardener.cloud/class` for control plane issuers …
```
=> Add annotation `cert.gardener.cloud/class` for control plane issuers

go.mod, go.sum, pkg/controller/extension/shared/assets/crd-cert.gardener.cloud_certificates.yaml
/area open-source
/kind task
Update [cert-management](https://github.com/gardener/cert-management) to [v0.17.8](https://github.com/gardener/cert-management/releases/tag/v0.17.8).
_n.a._
/cc @MartinWeindel 
```other dependency
Updated `cert-management` to `v0.17.8`.
```
=> chore: Update cert-management to v0.17.8

docs/tutorials/tutorial-custom-domain-with-istio.md, example/10-fake-shoot-controlplane.yaml, example/30-cluster.yaml, hack/api-reference/config.json, hack/api-reference/config.md, hack/api-reference/service.json, renovate.json5
Drop support for Shoots, Seeds and Gardens with Kubernetes version <= 1.28.
Part of https://github.com/gardener/gardener/issues/12409
N/A
```other operator
`shoot-cert-service` no longer supports Shoots with Кubernetes version <= 1.28.
```
=> Drop support for Shoots with Kubernetes version <= 1.28

renovate.json5
/area dev-productivity
Changes the Renovate configuration to group all updates related to Go, such as:
* https://github.com/gardener/gardener-extension-shoot-cert-service/pull/451
* https://github.com/gardener/gardener-extension-shoot-cert-service/pull/450
After merging this PR, the ones above should be automatically closed by Renovate and reopened as a single PR.
_n.a._
/cc @MartinWeindel 
```other operator
NONE
```
=> chore: Group Go Renovate updates

renovate.json5
/area dev-productivity
Uses the shared Renovate preset for grouping Go updates:
https://github.com/gardener/ci-infra/blob/master/config/renovate/group-go-updates.json5
Follow-up to:
* https://github.com/gardener/gardener-extension-shoot-cert-service/pull/452
_n.a._
/cc @MartinWeindel 
```other operator
NONE
```
=> chore: Use Renovate preset for grouping Go updates

.github/workflows/build.yaml
/kind task
Update build workflow to use Go 1.25 for `verify` step.
Fixes #
```other operator
NONE
```
=> Update build workflow to use Go 1.25 for verify step
